org: maneveil
service: weather-api

provider:
  name: aws
  runtime: nodejs22.x
  stage: dev

custom:
  apiGatewayCaching:
    enabled: true

functions:
  getTimeline:
    handler: src/adapters/handlers/weatherHandler.getTimeline
    memorySize: 512
    events:
      - httpApi:
          method: GET
          path: /weather/{location}

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    external:
      - '@aws-sdk/*'

package:
  individually: true
  patterns:
    - '!.idea/**'
    - '!coverage/**'
    - '!node_modules/**'
    - '.env'
  exclude:
    - .git/**/**

plugins:
  - serverless-api-gateway-caching
